# [mkdocs](https://www.mkdocs.org/)
# pip install --user -r docs/requirements.txt
# mkdocs build
# mkdocs gh-deploy
# mkdocs serve
site_name: Samuel Larkin's Documenation
site_url: https://SamuelLarkin.github.io
repo_url: https://github.com/SamuelLarkin/config
repo_name: SamuelLarkin/config
theme:
  name: material
  favicon: favicon-32x32.png
  palette:
    # Palette toggle for dark mode
    - primary: blue
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

    # Palette toggle for light mode
    - accent: light blue
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  features:
    - content.code.copy
    - content.code.select
    - announce.dismiss
  highlightjs: true
  hljs_languages:
    - bash
    - go
    - python
    - rust
    - yaml
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s
plugins:
  - search
  - macros
extra:
  homepage: https://github.com/SamuelLarkin/config
  version:
    provider: mike
    default: stable
markdown_extensions:
  - admonition
#  - pymdownx.details
#  - pymdownx.superfences
  - toc:
      permalink: true
nav:
  - Home: README.md
  - Colors: color.md
  - Configuration File Explained: config_files.md
  - fzf: fzf.md
  - Miscellaneous: doc.md
  - nvim: nvim.md
  - rsync: rsync.md
  - SLURM: slurm.md
  - tmux: tmux.md
