# You need to enable github to host your pages.
# github.com > Settings > Pages > Build and deployment:
# > Source > Deploy from a branches
# > Branch > gh-pages / `/root`
name: Deploy docs

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    paths:
      - "**.md"
      - "mkdocs.yml"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

# [source](https://zensical-action.cssnr.com/#features)
jobs:
  docs:
    name: 'Docs'
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.zensical.outputs.page_url }}

    steps:
      - name: 'Zensical Action'
        id: zensical
        uses: cssnr/zensical-action@v1
